export interface Tooltip {
  id: string;
  title: string;
  tooltip: string;
}

// Import tooltips from the synced file
// This file will be generated by the sync-content.sh script
let tooltips: Tooltip[] = [];

try {
  // Dynamic import to handle the case where the file might not exist yet
  const tooltipsModule = require('./tooltips');
  tooltips = tooltipsModule.tooltips || [];
} catch (error) {
  // If the tooltips file doesn't exist yet, use an empty array
  console.warn('Tooltips file not found. Run the sync script to fetch tooltips.');
}

/**
 * Get a tooltip by its ID
 * @param id - The tooltip ID to look up
 * @returns The tooltip object if found, otherwise undefined
 */
export function getTooltipById(id: string): Tooltip | undefined {
  return tooltips.find(t => t.id === id);
}

// Re-export tooltips array for direct access if needed
export { tooltips };
