replicaCount: 1
service:
  enabled: true
  name: '${APP_NAME}'

  port: ${PORT}
  type: ClusterIP
  containerPort: ${PORT}
  tls:
    enabled: true
    issuerName: cloudflare

image:
  repository: '${ECR_REGISTRY}/${ECR_REPO_NAME}'
  tag: '${IMAGE_TAG}'
  pullPolicy: Always

serviceAccount:
  create: false

ingress:
  enabled: true
  hosts:
    - '${ENDPOINT}'
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'

httpBasicAuth:
  enabled: false

# If enabled will create Traefik Middleware and apply to Ingress
# to redirect http to https and www to non-www
httpWwwRedirect:
  enabled: false

podAnnotations:
  reloader.stakater.com/auto: 'true'

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 300Mi

livenessProbe:
  httpGet:
    port: ${PORT}
  initialDelaySeconds: 6
  periodSeconds: 20
readinessProbe:
  httpGet:
    port: ${PORT}
  initialDelaySeconds: 6
  periodSeconds: 20

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - on-demand
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - '${APP_NAME}'
        topologyKey: "kubernetes.io/hostname"

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: '${APP_NAME}'

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: ${MAX_REPLICAS}
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
  scaleUp:
    stabilizationWindowSeconds: 30
    policyType: Pods
    value: ${MAX_REPLICAS}
    periodSeconds: 15
  scaleDown:
    stabilizationWindowSeconds: 300
    policyType: Pods
    value: 1
    periodSeconds: 30
