import { FAQItem } from './faqData';

export const skyTokens: FAQItem[] = [
  {
    question: 'What is USDS?',
    answer: `USDS is the stablecoin of the decentralized Sky Protocol. It can be used in several ways, including to participate in the Sky Savings Rate and access Sky Token Rewards without giving up control. It is the upgraded version of DAI, backed by a surplus of collateral and soft-pegged to the value of the U.S. dollar, meaning it is designed to maintain a value equal to or close to a dollar. USDS powers the permissionless, non-custodial Sky Protocol. 

Unlike cryptocurrencies that can fluctuate widely in value, USDS is designed to maintain a soft peg to the U.S. dollar and to be a reliable store of value and medium of exchange. USDS is governed by a community of broad and diversified individuals and entities from around the world, who hold Sky governance tokens and support the Sky ecosystem by participating in a system of decentralized onchain voting. USDS powers the open Sky ecosystem.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'How do I get USDS?',
    answer: `You can use Sky.money as a gateway to the Sky Protocol and to then access the permissionless liquidity pools, or similar onchain solutions, to trade USDC, USDT, ETH or SKY for USDS. You can also upgrade your DAI to USDS subject to any applicable gas fees for using the Ethereum blockchain network, which powers the Sky Protocol. That fee is not controlled, imposed, or received by Sky.money or the Sky Protocol. You might be able to obtain USDS on various crypto exchanges that decide to make it available on their platforms.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'How can I use USDS?',
    answer: `Like other decentralized stablecoins, USDS is freely transferable and can be used in connection with any software protocol or platform that supports it. Unlike other stablecoins, you can use USDS to access the Sky Savings Rate to accumulate additional USDS over time, and to access Sky Token Rewards without giving up control of your digital funds. With Sky Token Rewards, you can participate—if you choose to do so— in the governance of the Sky ecosystem.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'What is SKY, and how can I get it and use it?',
    answer: `SKY is a native governance token of the decentralized Sky ecosystem and the upgraded version of Maker's legacy governance token, MKR. You can upgrade your MKR to SKY at the rate of 1:24,000 via the Sky Protocol. 

You can trade SKY for USDS and, soon, use it to accumulate Activation Token Rewards and participate in Sky ecosystem governance through a system of decentralized onchain voting. 

Sky.money is a non-custodial gateway to the Sky Protocol. You always remain in control of your funds.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'What is DAI?',
    answer: `DAI is a widely used decentralized stablecoin generated by users through the Maker Protocol. It is backed by a surplus of collateral, soft-pegged to the value of the U.S. dollar, and easily user-generated and accessed. Eligible users holding DAI can upgrade it to the USDS stablecoin, which powers the open Sky ecosystem. 

As a Maker legacy token, DAI is maintained by, and will continue to be maintained by (unless the Sky ecosystem governance community decides otherwise) the Sky ecosystem. Users can continue to hold DAI, use DAI, maintain existing DAI Vaults and benefit from DAI Savings Rate (DSR) as they always have, and projects that have integrated DAI can continue to operate their frontends.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'What is MKR?',
    answer: `MKR is the native governance token of the Maker Protocol. MKR is now a governance token of the Sky Protocol, formerly the Maker Protocol. MKR holders use the token to vote on proposed changes and additions to the Sky Protocol, such as adjusting risk parameters, adding new collateral types, and more. 

As a Maker Protocol legacy token, MKR is maintained by, and will continue to be maintained by (unless the Sky ecosystem governance community decides otherwise) the Sky ecosystem.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'Are DAI and MKR going away?',
    answer: `Sky governance has not indicated that DAI and MKR are going away. Accordingly, they are expected to remain unaltered in their original forms for the foreseeable future, unless Sky governance decides otherwise. In the meantime, you can continue to hold and use both tokens exactly as you have in the past. While each token now has an upgraded version, the decision to upgrade your tokens is optional. 

Note that decisions regarding the decentralized Sky Protocol, its tokens, and features are made by Sky ecosystem governance token holders through a system of decentralized on-chain voting.`,
    categories: ['Sky Tokens']
  },
  {
    question: `What happens to the DAI I've supplied to the DAI Savings Rate (DSR) contract?`,
    answer: `The DAI Savings Rate (DSR) contract remains unchanged for now, so you don't need to immediately do anything to your DAI in the DSR module. Eligible users can, however, withdraw their DSR position, upgrade their DAI to USDS, and then use their USDS to access the Sky Savings Rate.

When you supply USDS to the Sky Savings Rate module, you receive sUSDS savings tokens. When you choose to redeem your sUSDS for USDS—which you can do anytime—the total USDS you will receive will equal the amount you originally supplied, plus any rewards accumulated. No minimum supply amount is required to access the SSR, and you always maintain full control of your supplied funds, as this feature is non-custodial.`,
    categories: ['Sky Tokens']
  },
  {
    question: 'Can I borrow USDS like I borrowed DAI?',
    answer: `[Spark](http://Spark.fi), the very first Sky Star and already a top DeFi liquidity protocol, offers Easy Borrow, a feature that enables you to borrow USDS in a way that is similar to how DAI was supplied.`,
    categories: ['Sky Tokens']
  }
];
